[package]
name = "legendsof1f600"
version = "0.1.0"
authors = ["Nathan Jent <nathanjent@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.17"
specs = "0.7.0"
yaml-rust = "0.3.4"
rustc-serialize = "0.3.21"
