[package]
name = "legendsof1f600"
version = "0.1.0"
authors = ["Nathan Jent <nathanjent@gmail.com>"]

[[bin]]
name = "legendsof1f600"

[dependencies]
specs = "0.7.0"
yaml-rust = "0.3.4"
rustc-serialize = "0.3.21"
iron = "*"
router = "*"
rouille = "1.0.1"
semver = "0.5.0"
conduit = "0.8.0"
conduit-router = "0.8.0"
route-recognizer = "0.1.11"
